# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_to_portfolio.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(407, 307)
        Form.setStyleSheet("background-color: white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit_competitions_name = QtWidgets.QLineEdit(Form)
        self.edit_competitions_name.setStyleSheet("background-color: #ffffff;\n"
"border-radius: 5px;\n"
"color: black;\n"
"padding: 10px;\n"
"border: 2px solid #eeeeee;\n"
"\n"
"")
        self.edit_competitions_name.setObjectName("edit_competitions_name")
        self.verticalLayout.addWidget(self.edit_competitions_name)
        self.edit_date = QtWidgets.QDateEdit(Form)
        self.edit_date.setStyleSheet("background-color: #ffffff;\n"
"border-radius: 5px;\n"
"color: black;\n"
"padding: 10px;\n"
"border: 2px solid #eeeeee;\n"
"\n"
"")
        self.edit_date.setObjectName("edit_date")
        self.verticalLayout.addWidget(self.edit_date)
        self.cmb_place = QtWidgets.QComboBox(Form)
        self.cmb_place.setStyleSheet("background-color: #ffffff;\n"
"border-radius: 5px;\n"
"color: black;\n"
"padding: 10px;\n"
"border: 2px solid #eeeeee;\n"
"\n"
"")
        self.cmb_place.setObjectName("cmb_place")
        self.cmb_place.addItem("")
        self.cmb_place.addItem("")
        self.cmb_place.addItem("")
        self.cmb_place.addItem("")
        self.verticalLayout.addWidget(self.cmb_place)
        self.btn_add_photo = QtWidgets.QPushButton(Form)
        self.btn_add_photo.setStyleSheet("background-color: #eeeeee;\n"
"border-radius: 5px;\n"
"color: black;\n"
"padding: 10px;\n"
"border: 2px solid #eeeeee;\n"
"")
        self.btn_add_photo.setObjectName("btn_add_photo")
        self.verticalLayout.addWidget(self.btn_add_photo)
        self.lbl_error = QtWidgets.QLabel(Form)
        self.lbl_error.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lbl_error.setStyleSheet("color: red;")
        self.lbl_error.setText("")
        self.lbl_error.setObjectName("lbl_error")
        self.verticalLayout.addWidget(self.lbl_error)
        self.btn_add_to_portfolio = QtWidgets.QPushButton(Form)
        self.btn_add_to_portfolio.setStyleSheet("padding: 10px;\n"
"background-color: #4654f9;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.btn_add_to_portfolio.setObjectName("btn_add_to_portfolio")
        self.verticalLayout.addWidget(self.btn_add_to_portfolio)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.edit_competitions_name.setPlaceholderText(_translate("Form", "Название соревнований"))
        self.cmb_place.setItemText(0, _translate("Form", "1 (Победитель)"))
        self.cmb_place.setItemText(1, _translate("Form", "2 (Призер)"))
        self.cmb_place.setItemText(2, _translate("Form", "3 (Призер)"))
        self.cmb_place.setItemText(3, _translate("Form", "Участник"))
        self.btn_add_photo.setText(_translate("Form", "Добавить фотографию"))
        self.btn_add_to_portfolio.setText(_translate("Form", "Добавить в портфолио"))
