# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(505, 744)
        Form.setStyleSheet("background-color: white;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_profile_image = QtWidgets.QLabel(Form)
        self.lbl_profile_image.setMaximumSize(QtCore.QSize(80, 80))
        self.lbl_profile_image.setText("")
        self.lbl_profile_image.setPixmap(QtGui.QPixmap("ui/../images/user.png"))
        self.lbl_profile_image.setScaledContents(True)
        self.lbl_profile_image.setObjectName("lbl_profile_image")
        self.horizontalLayout.addWidget(self.lbl_profile_image)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name.setFont(font)
        self.lbl_name.setStyleSheet("color: #333c56;")
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.lbl_age = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_age.setFont(font)
        self.lbl_age.setStyleSheet("color: #333c56;")
        self.lbl_age.setObjectName("lbl_age")
        self.verticalLayout.addWidget(self.lbl_age)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_edit_profile = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_edit_profile.setFont(font)
        self.btn_edit_profile.setStyleSheet("background-color: #4654f9;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"color: white;\n"
"padding: 5px;")
        self.btn_edit_profile.setObjectName("btn_edit_profile")
        self.horizontalLayout_3.addWidget(self.btn_edit_profile)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn_delete_profile = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_delete_profile.setFont(font)
        self.btn_delete_profile.setStyleSheet("background-color: #fa4658;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"color: white;\n"
"padding: 5px;")
        self.btn_delete_profile.setObjectName("btn_delete_profile")
        self.horizontalLayout_3.addWidget(self.btn_delete_profile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_add_img_to_portfolio = QtWidgets.QPushButton(Form)
        self.btn_add_img_to_portfolio.setStyleSheet("padding: 10px;\n"
"background-color: #4654f9;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.btn_add_img_to_portfolio.setObjectName("btn_add_img_to_portfolio")
        self.horizontalLayout_2.addWidget(self.btn_add_img_to_portfolio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.feed_portfolio = QPortfolioFeed(Form)
        self.feed_portfolio.setWidgetResizable(True)
        self.feed_portfolio.setObjectName("feed_portfolio")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 485, 555))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.feed_portfolio.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.feed_portfolio)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_name.setText(_translate("Form", "TImur Pavlov"))
        self.lbl_age.setText(_translate("Form", "15 age"))
        self.btn_edit_profile.setText(_translate("Form", "Редактировать профиль"))
        self.btn_delete_profile.setText(_translate("Form", "Удалить профиль"))
        self.btn_add_img_to_portfolio.setText(_translate("Form", "Добавить фото в портфолио"))
from qportfoliofeed import QPortfolioFeed
