# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_to_portfolio.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(421, 246)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 144))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.edit_competitions_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit_competitions_name.setObjectName("edit_competitions_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_competitions_name)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.edit_date = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.edit_date.setObjectName("edit_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_date)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cmb_place = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmb_place.setObjectName("cmb_place")
        self.cmb_place.addItem("")
        self.cmb_place.addItem("")
        self.cmb_place.addItem("")
        self.cmb_place.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmb_place)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.btn_add_photo = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_add_photo.setObjectName("btn_add_photo")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btn_add_photo)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.btn_add_to_portfolio = QtWidgets.QPushButton(Form)
        self.btn_add_to_portfolio.setGeometry(QtCore.QRect(240, 210, 172, 25))
        self.btn_add_to_portfolio.setObjectName("btn_add_to_portfolio")
        self.lbl_error = QtWidgets.QLabel(Form)
        self.lbl_error.setGeometry(QtCore.QRect(10, 170, 67, 17))
        self.lbl_error.setStyleSheet("color: red;")
        self.lbl_error.setText("")
        self.lbl_error.setObjectName("lbl_error")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Дата проведения:"))
        self.label_3.setText(_translate("Form", "Место:"))
        self.cmb_place.setItemText(0, _translate("Form", "1 (Победитель)"))
        self.cmb_place.setItemText(1, _translate("Form", "2 (Призер)"))
        self.cmb_place.setItemText(2, _translate("Form", "3 (Призер)"))
        self.cmb_place.setItemText(3, _translate("Form", "Участник"))
        self.label_4.setText(_translate("Form", "Фотография:"))
        self.btn_add_photo.setText(_translate("Form", "Добавить фотографию"))
        self.label.setText(_translate("Form", "Название соревнований:"))
        self.btn_add_to_portfolio.setText(_translate("Form", "Добавить в портфолио"))
