# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/app_teacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(615, 822)
        Form.setStyleSheet("background-color: white;")
        self.tabs = QtWidgets.QTabWidget(Form)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 605, 802))
        self.tabs.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabs.setObjectName("tabs")
        self.tab_profile = ProfileTab()
        self.tab_profile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_profile.setObjectName("tab_profile")
        self.tabs.addTab(self.tab_profile, "")
        self.tab_manage_tasks = ManageTasksTab()
        self.tab_manage_tasks.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_manage_tasks.setObjectName("tab_manage_tasks")
        self.tabs.addTab(self.tab_manage_tasks, "")
        self.tab_create_class = CreateClassTab()
        self.tab_create_class.setObjectName("tab_create_class")
        self.tabs.addTab(self.tab_create_class, "")

        self.retranslateUi(Form)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_profile), _translate("Form", "Профиль"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_manage_tasks), _translate("Form", "Создать задание"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_create_class), _translate("Form", "Создать класс"))
from create_class import CreateClassTab
from profile import ProfileTab
from tasks import ManageTasksTab
