# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login_account.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(312, 228)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 90, 271, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.edit_email = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit_email.setObjectName("edit_email")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_email)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.edit_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_password.setObjectName("edit_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_password)
        self.btn_login = QtWidgets.QPushButton(Form)
        self.btn_login.setGeometry(QtCore.QRect(110, 190, 89, 25))
        self.btn_login.setObjectName("btn_login")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(120, 20, 79, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lbl_info = QtWidgets.QLabel(Form)
        self.lbl_info.setGeometry(QtCore.QRect(20, 160, 67, 17))
        self.lbl_info.setStyleSheet("color: red;")
        self.lbl_info.setText("")
        self.lbl_info.setObjectName("lbl_info")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Почта:"))
        self.label.setText(_translate("Form", "Пароль:"))
        self.btn_login.setText(_translate("Form", "Войти"))
        self.label_3.setText(_translate("Form", "Логин"))
