# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/manage_tasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAcceptDrops(False)
        Form.setToolTipDuration(-1)
        Form.setStyleSheet("background-color: white;")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 431, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit_title = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_title.setStyleSheet("background-color: #ffffff;\n"
"border-radius: 5px;\n"
"color: black;\n"
"padding: 10px;\n"
"border: 2px solid #eeeeee;")
        self.edit_title.setObjectName("edit_title")
        self.verticalLayout.addWidget(self.edit_title)
        self.edit_text = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.edit_text.setStyleSheet("background-color: #ffffff;\n"
"border-radius: 5px;\n"
"color: black;\n"
"padding: 10px;\n"
"border: 2px solid #eeeeee;")
        self.edit_text.setObjectName("edit_text")
        self.verticalLayout.addWidget(self.edit_text)
        self.dtchoice_date = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dtchoice_date.setStyleSheet("background-color: #ffffff;\n"
"border-radius: 5px;\n"
"color: black;\n"
"padding: 10px;\n"
"border: 2px solid #eeeeee;")
        self.dtchoice_date.setObjectName("dtchoice_date")
        self.verticalLayout.addWidget(self.dtchoice_date)
        self.btn_add_material = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_add_material.setStyleSheet("background-color: #eeeeee;\n"
"border-radius: 5px;\n"
"color: black;\n"
"padding: 10px;\n"
"border: 2px solid #eeeeee;\n"
"")
        self.btn_add_material.setObjectName("btn_add_material")
        self.verticalLayout.addWidget(self.btn_add_material)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("color: red;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_send = QtWidgets.QPushButton(Form)
        self.btn_send.setGeometry(QtCore.QRect(290, 360, 161, 37))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_send.setFont(font)
        self.btn_send.setStyleSheet("padding: 10px;\n"
"background-color: #4654f9;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.btn_send.setObjectName("btn_send")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.edit_title.setPlaceholderText(_translate("Form", "Заголовк"))
        self.edit_text.setPlaceholderText(_translate("Form", "Текст задания"))
        self.btn_add_material.setText(_translate("Form", "Загрузить пример, материал"))
        self.btn_send.setText(_translate("Form", "Отправить"))
