# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/profile_children.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 822)
        Form.setStyleSheet("background-color: white;")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 605, 802))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.feed_portfolio = QPortfolioFeed(self.tab)
        self.feed_portfolio.setGeometry(QtCore.QRect(10, 210, 581, 551))
        self.feed_portfolio.setWidgetResizable(True)
        self.feed_portfolio.setObjectName("feed_portfolio")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 549))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.feed_portfolio.setWidget(self.scrollAreaWidgetContents)
        self.btn_edit_profile = QtWidgets.QPushButton(self.tab)
        self.btn_edit_profile.setGeometry(QtCore.QRect(10, 90, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_edit_profile.setFont(font)
        self.btn_edit_profile.setStyleSheet("background-color: #4654f9;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.btn_edit_profile.setObjectName("btn_edit_profile")
        self.lbl_name = QtWidgets.QLabel(self.tab)
        self.lbl_name.setGeometry(QtCore.QRect(90, 10, 180, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_age = QtWidgets.QLabel(self.tab)
        self.lbl_age.setGeometry(QtCore.QRect(90, 50, 67, 17))
        self.lbl_age.setObjectName("lbl_age")
        self.btn_add_img_to_portfolio = QtWidgets.QPushButton(self.tab)
        self.btn_add_img_to_portfolio.setGeometry(QtCore.QRect(10, 160, 226, 39))
        self.btn_add_img_to_portfolio.setStyleSheet("padding: 10px;\n"
"background-color: #4654f9;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.btn_add_img_to_portfolio.setObjectName("btn_add_img_to_portfolio")
        self.lbl_profile_image = QtWidgets.QLabel(self.tab)
        self.lbl_profile_image.setGeometry(QtCore.QRect(10, 10, 65, 65))
        self.lbl_profile_image.setText("")
        self.lbl_profile_image.setPixmap(QtGui.QPixmap("ui/../../../.designer/images/user.png"))
        self.lbl_profile_image.setScaledContents(True)
        self.lbl_profile_image.setObjectName("lbl_profile_image")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tbl_tasks = QtWidgets.QTableWidget(self.tab_2)
        self.tbl_tasks.setEnabled(True)
        self.tbl_tasks.setGeometry(QtCore.QRect(10, 10, 581, 351))
        self.tbl_tasks.setStyleSheet("")
        self.tbl_tasks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_tasks.setDragEnabled(False)
        self.tbl_tasks.setAlternatingRowColors(False)
        self.tbl_tasks.setShowGrid(True)
        self.tbl_tasks.setGridStyle(QtCore.Qt.SolidLine)
        self.tbl_tasks.setWordWrap(True)
        self.tbl_tasks.setCornerButtonEnabled(True)
        self.tbl_tasks.setObjectName("tbl_tasks")
        self.tbl_tasks.setColumnCount(4)
        self.tbl_tasks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tasks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tasks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tasks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tasks.setHorizontalHeaderItem(3, item)
        self.tbl_tasks.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_tasks.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_tasks.horizontalHeader().setStretchLastSection(True)
        self.tbl_tasks.verticalHeader().setVisible(False)
        self.tbl_tasks.verticalHeader().setHighlightSections(True)
        self.tbl_tasks.verticalHeader().setSortIndicatorShown(False)
        self.tbl_tasks.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_edit_profile.setText(_translate("Form", "Редактировать профиль"))
        self.lbl_name.setText(_translate("Form", "TImur Pavlov"))
        self.lbl_age.setText(_translate("Form", "15 age"))
        self.btn_add_img_to_portfolio.setText(_translate("Form", "Добавить фото в портфолио"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Профиль"))
        self.tbl_tasks.setSortingEnabled(True)
        item = self.tbl_tasks.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Дата"))
        item = self.tbl_tasks.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Название"))
        item = self.tbl_tasks.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Содержание"))
        item = self.tbl_tasks.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Фотография материала, примера"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Задания"))
from qportfoliofeed import QPortfolioFeed
