# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 771)
        Form.setStyleSheet("background-color: white;")
        self.btn_add_img_to_portfolio = QtWidgets.QPushButton(Form)
        self.btn_add_img_to_portfolio.setGeometry(QtCore.QRect(10, 160, 226, 39))
        self.btn_add_img_to_portfolio.setStyleSheet("padding: 10px;\n"
"background-color: #4654f9;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.btn_add_img_to_portfolio.setObjectName("btn_add_img_to_portfolio")
        self.lbl_age = QtWidgets.QLabel(Form)
        self.lbl_age.setGeometry(QtCore.QRect(90, 50, 67, 17))
        self.lbl_age.setObjectName("lbl_age")
        self.feed_portfolio = QPortfolioFeed(Form)
        self.feed_portfolio.setGeometry(QtCore.QRect(10, 210, 481, 551))
        self.feed_portfolio.setWidgetResizable(True)
        self.feed_portfolio.setObjectName("feed_portfolio")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 549))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.feed_portfolio.setWidget(self.scrollAreaWidgetContents)
        self.btn_edit_profile = QtWidgets.QPushButton(Form)
        self.btn_edit_profile.setGeometry(QtCore.QRect(10, 90, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_edit_profile.setFont(font)
        self.btn_edit_profile.setStyleSheet("background-color: #4654f9;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.btn_edit_profile.setObjectName("btn_edit_profile")
        self.lbl_profile_image = QtWidgets.QLabel(Form)
        self.lbl_profile_image.setGeometry(QtCore.QRect(10, 10, 65, 65))
        self.lbl_profile_image.setText("")
        self.lbl_profile_image.setPixmap(QtGui.QPixmap("ui/../images/user.png"))
        self.lbl_profile_image.setScaledContents(True)
        self.lbl_profile_image.setObjectName("lbl_profile_image")
        self.lbl_name = QtWidgets.QLabel(Form)
        self.lbl_name.setGeometry(QtCore.QRect(90, 10, 180, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName("lbl_name")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_add_img_to_portfolio.setText(_translate("Form", "Добавить фото в портфолио"))
        self.lbl_age.setText(_translate("Form", "15 age"))
        self.btn_edit_profile.setText(_translate("Form", "Редактировать профиль"))
        self.lbl_name.setText(_translate("Form", "TImur Pavlov"))
from qportfoliofeed import QPortfolioFeed
