# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/tasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(598, 374)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbl_tasks = QtWidgets.QTableWidget(Form)
        self.tbl_tasks.setEnabled(True)
        self.tbl_tasks.setStyleSheet("")
        self.tbl_tasks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_tasks.setDragEnabled(False)
        self.tbl_tasks.setAlternatingRowColors(False)
        self.tbl_tasks.setShowGrid(True)
        self.tbl_tasks.setGridStyle(QtCore.Qt.SolidLine)
        self.tbl_tasks.setWordWrap(True)
        self.tbl_tasks.setCornerButtonEnabled(True)
        self.tbl_tasks.setObjectName("tbl_tasks")
        self.tbl_tasks.setColumnCount(4)
        self.tbl_tasks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tasks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tasks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tasks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tasks.setHorizontalHeaderItem(3, item)
        self.tbl_tasks.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_tasks.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_tasks.horizontalHeader().setStretchLastSection(True)
        self.tbl_tasks.verticalHeader().setVisible(False)
        self.tbl_tasks.verticalHeader().setHighlightSections(True)
        self.tbl_tasks.verticalHeader().setSortIndicatorShown(False)
        self.tbl_tasks.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tbl_tasks)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tbl_tasks.setSortingEnabled(True)
        item = self.tbl_tasks.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Дата"))
        item = self.tbl_tasks.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Название"))
        item = self.tbl_tasks.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Содержание"))
        item = self.tbl_tasks.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Фотография материала, примера"))
